defmodule AshGrant.Test.Article do
  @moduledoc """
  Test resource demonstrating `default_policies: true` feature (v0.2.0).

  This resource shows the minimal configuration approach where policies
  are auto-generated by `AshGrant.Transformers.AddDefaultPolicies`.

  ## Key Features Demonstrated

  - `default_policies: true` - No manual policy block needed
  - Inline scope DSL with `expr()` expressions
  - Anonymous function resolver for role-based permissions
  - Proper `^actor(:id)` template usage in scopes

  ## Generated Policies

  The transformer automatically generates:

      policies do
        policy action_type(:read) do
          authorize_if AshGrant.filter_check()
        end

        policy action_type([:create, :update, :destroy]) do
          authorize_if AshGrant.check()
        end

        policy action_type(:action) do
          authorize_if AshGrant.check()
        end
      end

  ## Role Permissions

  | Role | Permissions |
  |------|-------------|
  | admin | `article:*:*:all` - Full access |
  | editor | Read all, update own, create all |
  | viewer | Read published only |
  """
  use Ash.Resource,
    domain: AshGrant.Test.Domain,
    data_layer: AshPostgres.DataLayer,
    authorizers: [Ash.Policy.Authorizer],
    extensions: [AshGrant]

  postgres do
    table("articles")
    repo(AshGrant.TestRepo)
  end

  ash_grant do
    resolver(fn actor, _context ->
      case actor do
        nil -> []
        %{permissions: perms} -> perms
        %{role: :admin} -> ["article:*:*:all"]
        %{role: :editor} -> ["article:*:read:all", "article:*:update:own", "article:*:create:all"]
        %{role: :viewer} -> ["article:*:read:published"]
        _ -> []
      end
    end)

    default_policies(true)
    resource_name("article")

    scope(:all, true)
    scope(:own, expr(author_id == ^actor(:id)))
    scope(:published, expr(status == :published))
  end

  # No policies block needed - default_policies: true generates them!

  attributes do
    uuid_primary_key(:id)
    attribute(:title, :string, public?: true, allow_nil?: false)
    attribute(:body, :string, public?: true)

    attribute :status, :atom do
      constraints(one_of: [:draft, :published])
      default(:draft)
      public?(true)
    end

    attribute(:author_id, :uuid, public?: true)
    create_timestamp(:inserted_at)
    update_timestamp(:updated_at)
  end

  actions do
    defaults([:read, :destroy, create: :*, update: :*])

    action :summarize, :string do
      run(fn _input, _context -> {:ok, "summary"} end)
    end
  end
end
